enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

[GooglePhotos]
enabled = false
build-mode = "both"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"

[Twitch]
enabled = false
build-mode = "apk"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch/"

[Music-Extended]
enabled = false
app-name = "Music"
build-mode = "apk"
arch = "arm64-v8a"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"

[YouTube-Extended]
enabled = false
app-name = "YouTube"
build-mode = "both"
arch = "arm64-v8a"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"

[YouTube]
enabled = false
build-mode = "both"
arch = "arm64-v8a"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"

[Reddit-Extended]
enabled = false
app-name = "Reddit"
build-mode = "apk"
arch = "arm64-v8a"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"

[Reddit]
enabled = false
build-mode = "apk"
arch = "arm64-v8a"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"

[TikTok]
enabled = false
build-mode = "apk"
arch = "arm64-v8a"
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"

[Messenger]
#enabled = false
build-mode = "module"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"

[Facebook]
enabled = false
build-mode = "module"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook/"

